[package]
authors = ["Erik Johnston"]
description = "A tool to compress some state in a Synapse instance's database"
edition = "2018"
name = "synapse-compress-state"
version = "0.1.0"

[dependencies]
clap = "2.32.0"
fallible-iterator = "0.1.5"
indicatif = "0.11.0"
jemallocator = "0.3.0"
postgres = "0.15.2"
rand = "0.6.0"
rayon = "1.0.2"
string_cache = "0.7.3"

[dependencies.state-map]
git = "https://github.com/matrix-org/rust-matrix-state-map"
